DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID INT AUTO_INCREMENT PRIMARY KEY , NAME VARCHAR(255));

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID INT AUTO_INCREMENT PRIMARY KEY , NAME VARCHAR(255));

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(
                      ID INT AUTO_INCREMENT PRIMARY KEY,
                      NAME VARCHAR(255),
                      AUTHOR_ID BIGINT NOT NULL,
                      GENRE_ID BIGINT NOT NULL,
                      foreign key (AUTHOR_ID) references AUTHORS(ID),
                      foreign key (GENRE_ID) references GENRES(ID)
);

DROP TABLE IF EXISTS COMMENTS;
CREATE TABLE COMMENTS(
                         ID INT AUTO_INCREMENT PRIMARY KEY,
                         BOOK_ID BIGINT,
                         DATA VARCHAR(255),
                         foreign key (BOOK_ID) references BOOKS(ID) ON DELETE CASCADE
);

DROP TABLE IF EXISTS APP_USER;
create table APP_USER
(
    ID                INT AUTO_INCREMENT PRIMARY KEY,
    LOGIN             VARCHAR(255) not null,
    PASSWORD          VARCHAR(255) not null,
    USER_ROLE         VARCHAR(255) not null
);


DROP TABLE IF EXISTS acl_sid;
CREATE TABLE acl_sid (
    id bigint generated by default as identity(start with 100) not   null primary key,
    principal int NOT NULL,
    sid varchar(100) NOT NULL
    );

DROP TABLE IF EXISTS acl_class;
CREATE TABLE IF NOT EXISTS acl_class (
    id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    class varchar(255) NOT NULL,
    PRIMARY KEY (id)
    );

DROP TABLE IF EXISTS acl_entry;
CREATE TABLE IF NOT EXISTS acl_entry (
    id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    acl_object_identity int NOT NULL,
    ace_order int NOT NULL,
    sid int NOT NULL,
    mask int NOT NULL,
    granting int NOT NULL,
    audit_success int NOT NULL,
    audit_failure int NOT NULL
    );
DROP TABLE IF EXISTS acl_object_identity;
CREATE TABLE IF NOT EXISTS acl_object_identity (
    id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    object_id_class int NOT NULL,
    object_id_identity int NOT NULL,
    parent_object int DEFAULT NULL,
    owner_sid int DEFAULT NULL,
    entries_inheriting int NOT NULL
    );

/*

ALTER TABLE acl_entry
    ADD FOREIGN KEY (acl_object_identity) REFERENCES acl_object_identity(id);

ALTER TABLE acl_entry
    ADD FOREIGN KEY (sid) REFERENCES acl_sid(id);

--
-- Constraints for table acl_object_identity
--
ALTER TABLE acl_object_identity
    ADD FOREIGN KEY (parent_object) REFERENCES acl_object_identity (id);

ALTER TABLE acl_object_identity
    ADD FOREIGN KEY (object_id_class) REFERENCES acl_class (id);

ALTER TABLE acl_object_identity
    ADD FOREIGN KEY (owner_sid) REFERENCES acl_sid (id);*/