spring:
  data:
    mongodb:
      database: booklib
      host: 192.168.10.99

mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.spring08.mongock.changelog