spring:
  output:
    ansi:
      enabled: always
  banner:
    location: banner.txt
  messages:
    encoding: UTF-8
  main:
    allow-circular-references: true

application:
  title: Exam student
  version: 0.3.2

exam:
  min_correct_answers: 4
  question_file: questions_%s.csv
  locale: en-US   # ru-RU / en-US